[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
fs_permissions = [{ access = "read", path = "lib/foundry-chainlink-toolkit/out"}]
test = "test"
cache_path = "cache"
via_ir = true
fuzz = { runs = 1000 }

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[profile.intense]
fuzz = { runs = 50000 }
invariant = { runs = 10000 }

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config